[alembic]
script_location = alembic
sqlalchemy.url = postgresql+psycopg2://postgres:%%EC%%98%%81%%EB%%A6%%AC%%ED%%95%%9C12%%21%%40@dev.c2r.co.kr:45432/postgres?options=-csearch_path%%3Dcleversearch_dev

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
